import { EventEmitter2 } from '@nestjs/event-emitter';
import { PrismaService } from '../database/prisma.service';
import { RedisService } from '../redis/redis.service';
import { JoinQueueInput } from './dto/join-queue.input';
import { UpdateQueueStatusInput } from './dto/update-queue-status.input';
export declare class QueueService {
    private readonly prisma;
    private readonly redis;
    private readonly eventEmitter;
    private readonly logger;
    constructor(prisma: PrismaService, redis: RedisService, eventEmitter: EventEmitter2);
    joinQueue(input: JoinQueueInput, customerId?: string, allowedShopIds?: string[]): Promise<{
        id: string;
        shopId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.QueueStatus;
        branchId: string;
        estimatedWaitMins: number;
        ticketNumber: number;
        priority: number;
        position: number;
        barberId: string;
        customerId: string;
        guestPhone: string;
        guestName: string;
        serviceId: string;
        ticketDisplay: string;
        entryType: import(".prisma/client").$Enums.EntryType;
        joinedAt: Date;
        calledAt: Date;
        servingAt: Date;
        servedAt: Date;
        leftAt: Date;
        noShowAt: Date;
        appointmentId: string;
        notes: string;
    }>;
    getActiveQueue(shopId: string, barberId?: string): Promise<{
        id: string;
        shopId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.QueueStatus;
        branchId: string;
        estimatedWaitMins: number;
        ticketNumber: number;
        priority: number;
        position: number;
        barberId: string;
        customerId: string;
        guestPhone: string;
        guestName: string;
        serviceId: string;
        ticketDisplay: string;
        entryType: import(".prisma/client").$Enums.EntryType;
        joinedAt: Date;
        calledAt: Date;
        servingAt: Date;
        servedAt: Date;
        leftAt: Date;
        noShowAt: Date;
        appointmentId: string;
        notes: string;
    }[]>;
    getEntryById(entryId: string, allowedShopIds?: string[]): Promise<{
        id: string;
        shopId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.QueueStatus;
        branchId: string;
        estimatedWaitMins: number;
        ticketNumber: number;
        priority: number;
        position: number;
        barberId: string;
        customerId: string;
        guestPhone: string;
        guestName: string;
        serviceId: string;
        ticketDisplay: string;
        entryType: import(".prisma/client").$Enums.EntryType;
        joinedAt: Date;
        calledAt: Date;
        servingAt: Date;
        servedAt: Date;
        leftAt: Date;
        noShowAt: Date;
        appointmentId: string;
        notes: string;
    }>;
    getQueueStats(shopId: string, barberId?: string): Promise<{
        waitingCount: number;
        servingCount: number;
        avgWaitMins: number;
        servedTodayCount: number;
    }>;
    updateStatus(input: UpdateQueueStatusInput, actorId: string, allowedShopIds?: string[]): Promise<{
        id: string;
        shopId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.QueueStatus;
        branchId: string;
        estimatedWaitMins: number;
        ticketNumber: number;
        priority: number;
        position: number;
        barberId: string;
        customerId: string;
        guestPhone: string;
        guestName: string;
        serviceId: string;
        ticketDisplay: string;
        entryType: import(".prisma/client").$Enums.EntryType;
        joinedAt: Date;
        calledAt: Date;
        servingAt: Date;
        servedAt: Date;
        leftAt: Date;
        noShowAt: Date;
        appointmentId: string;
        notes: string;
    }>;
    leaveQueue(entryId: string, customerId: string, allowedShopIds?: string[]): Promise<{
        id: string;
        shopId: string;
        createdAt: Date;
        status: import(".prisma/client").$Enums.QueueStatus;
        branchId: string;
        estimatedWaitMins: number;
        ticketNumber: number;
        priority: number;
        position: number;
        barberId: string;
        customerId: string;
        guestPhone: string;
        guestName: string;
        serviceId: string;
        ticketDisplay: string;
        entryType: import(".prisma/client").$Enums.EntryType;
        joinedAt: Date;
        calledAt: Date;
        servingAt: Date;
        servedAt: Date;
        leftAt: Date;
        noShowAt: Date;
        appointmentId: string;
        notes: string;
    }>;
    recalculateQueue(shopId: string, barberId?: string): Promise<void>;
    private publishUpdate;
}
