import { PrismaService } from '../database/prisma.service';
import { CreateShopInput, UpdateShopInput } from './dto/create-shop.input';
export declare class ShopsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    createShop(ownerId: string, input: CreateShopInput): Promise<{
        name: string;
        description: string;
        id: string;
        phone: string;
        email: string;
        isVerified: boolean;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        ownerId: string;
        slug: string;
        logoUrl: string;
        country: string;
        timezone: string;
        currency: string;
    }>;
    findById(id: string, allowedShopIds?: string[]): Promise<{
        name: string;
        description: string;
        id: string;
        phone: string;
        email: string;
        isVerified: boolean;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        ownerId: string;
        slug: string;
        logoUrl: string;
        country: string;
        timezone: string;
        currency: string;
    }>;
    findBySlug(slug: string, allowedShopIds?: string[]): Promise<{
        name: string;
        description: string;
        id: string;
        phone: string;
        email: string;
        isVerified: boolean;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        ownerId: string;
        slug: string;
        logoUrl: string;
        country: string;
        timezone: string;
        currency: string;
    }>;
    findByOwner(ownerId: string, allowedShopIds?: string[]): Promise<{
        name: string;
        description: string;
        id: string;
        phone: string;
        email: string;
        isVerified: boolean;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        ownerId: string;
        slug: string;
        logoUrl: string;
        country: string;
        timezone: string;
        currency: string;
    }>;
    getBranches(shopId: string, allowedShopIds?: string[]): Promise<{
        name: string;
        id: string;
        phone: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        shopId: string;
        address: string;
        city: string;
        latitude: import("@prisma/client/runtime/library").Decimal;
        longitude: import("@prisma/client/runtime/library").Decimal;
        isMain: boolean;
    }[]>;
    updateShop(shopId: string, ownerId: string, input: UpdateShopInput): Promise<{
        name: string;
        description: string;
        id: string;
        phone: string;
        email: string;
        isVerified: boolean;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        ownerId: string;
        slug: string;
        logoUrl: string;
        country: string;
        timezone: string;
        currency: string;
    }>;
    private assertOwner;
    private generateUniqueSlug;
}
